version: "3.9"
   
services:
  db:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgresa
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  redis:
    image: "redis:alpine"
    ports: 
      - 6379:6379